---
- name: Install Docker
  hosts: invent
  become: true
  become_method: sudo

  vars:
    docker_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Add Docker repository
      block:
        - name: Install ca-certificates and curl  
          ansible.builtin.apt:
            name: 
              - ca-certificates
              - curl
            state: present
            update_cache: true
        - name: Install keyring
          ansible.builtin.command: install -m 0755 -d /etc/apt/keyrings
        - name: Download gpg key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/debian/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'
        - name: Add the repository to Apt sources
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
            state: present
            filename: docker.list

    - name: Install Docker
      ansible.builtin.apt:
        name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present
        update_cache: true

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true