---
- name: Install Nodejs
  hosts: invent
  become: true
  become_method: sudo

  vars:
    nodejs_user: "{{ lookup('env', 'USER') }}"
    nodejs_user_home: "/home"
    nodejs_version: "v22.15.0"
    nodejs_ver_arch: "node-{{ nodejs_version }}-linux-x64"
    nodejs_URL: "https://nodejs.org/dist/{{ nodejs_version }}/{{ nodejs_ver_arch }}.tar.xz"
    nodejs_install_dir: "/opt/{{ nodejs_ver_arch }}/bin"

  tasks:
    - name: Download Nodejs
      ansible.builtin.get_url:
        url: "{{ nodejs_URL }}"
        dest: /tmp/nodejs.tar.xz
        mode: '0644'
    - name: Extract Nodejs
      ansible.builtin.unarchive:
        src: /tmp/nodejs.tar.xz
        dest: /opt/
        remote_src: yes
    - name: Add Nodejs to PATH
      ansible.builtin.lineinfile:
        path: "{{ nodejs_user_home }}/{{ nodejs_user }}/.bashrc"
        line: 'export PATH={{ nodejs_install_dir }}:$PATH'
        state: present