---
- name: Install Docker
  hosts: invent
  become: true
  become_method: sudo

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Add Docker repository
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo

    - name: Install Docker
      ansible.builtin.package:
        name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true